version: '3'
services:
  goapi:
    container_name: goPlan
    build: .
    volumes:
      - .:/go/src/go/
    working_dir: /go/src/go
    command: go run main.go contoller.go structs.go scrapper.go
    ports:
    - "8080:8080"